### ISSUE TITLE
CURRÍCULO-ONLINE

### ISSUE THREAD

**Issue by JenniferSilva46** [AmandaSImoes1707/Projeto#1]
**O PROJETO É PRA CRIAR UM CURRÍCULO ONLINE USANDO HTML5 E ESTILIZANDO COM CSS3.** 
  Um bom currículo deve ter as seguintes seções:
Nome completo
Endereço
Contato (Email e telefone)
Formação acadêmica
Experiência profissional
Habilidades
Idiomas
Informações complementares
****

**Comment by AmandaSImoes1707** [comment]
Melhoria Efetuada

**Comment by AmandaSImoes1707** [comment]
Sessões concluídas com sucesso!
